### ISSUE TITLE
cache apihost supported runtimes

### ISSUE THREAD

**Issue by shazron** [adobe/aio-lib-runtime#102]
Right now the supported runtimes are static:
https://github.com/adobe/aio-lib-runtime/blob/822176f68d39b83571fb34d2698ddfa23aeb23df/src/utils.js#L24

On first run, cache the supported runtimes in the config, per apihost. There is the `utils.getSupportedServerRuntimes` function available.

**Comment by purplecabbage** [comment]
I think a better approach is just to wait for the call to fail and present a nice error message telling the user what to do. There should be one source of truth, so we do not need to update the client when the server changes.   
Caching values seems like extra code for something that changes infrequently.

**Comment by shazron** [comment]
We already do what you suggested. This was an enhancement.

**Comment by shazron** [comment]
fixed via https://github.com/adobe/aio-lib-runtime/pull/138
