### ISSUE TITLE
Bug: imsOrgId must be defined when using the Adobe headless auth validator

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-lib-runtime#166]
### Expected Behaviour

The headless auth validator is a thing of the past. Adobe auth checks, when `require-adobe-auth` is enabled, are now only made through the app-registry validator.

We need to clean up all the code that sets the org in state lib. 
https://github.com/adobe/aio-lib-runtime/blob/e8815561e7d7e06e75e8f4d8cc6ef69da12fb7d2/src/utils.js#L1444

### Workaround

A workaround is to set the `AIO_PROJECT_ORG_IMS__ORG__ID` environment variable.

### Fix

Remove the `setupAdobeAuth` function and all references: https://github.com/adobe/aio-lib-runtime/blob/e8815561e7d7e06e75e8f4d8cc6ef69da12fb7d2/src/utils.js#L1430

**Comment by shazron** [comment]
PR https://github.com/adobe/aio-lib-runtime/pull/167
