### ISSUE TITLE
npm config contains broken links

### ISSUE THREAD

**Issue by rabbah** [adobe/aio-lib-runtime#4]
### Expected Behaviour
on npm https://www.npmjs.com/package/@adobe/aio-lib-runtime notice the links to github are wrong - the first contains a `@` and the other `%40`.

<img width="392" alt="Screen Shot 2020-07-17 at 10 23 19 AM" src="https://user-images.githubusercontent.com/4959922/87796573-8aff1f80-c817-11ea-8d95-c632114c294b.png">

### Actual Behaviour

Proper links.

#### Steps to Reproduce
Visit https://www.npmjs.com/package/@adobe/aio-lib-runtime.
True as of v0.0.3.

**Comment by shazron** [comment]
I believe this is fixed by https://github.com/adobe/aio-lib-runtime/commit/b4a09e87596a0288bbd85800ba01bf506fa419c5 but unreleased
