### ISSUE TITLE
Likely flag parsing error when large numeric values

### ISSUE THREAD

**Issue by justinedelson** [adobe/aio-lib-runtime#47]
This is a placeholder until I test this fully (unless someone else wants to), but I received a bug report on the copy of `createKeyValueObjectFromFlag` I have in `aio-cli-plugin-cloudmanager`. Although that code moved from `aio-cli-plugin-runtime` to this project, it seems to still be the same.

### Expected Behaviour

`createKeyValueObjectFromFlag(['foo', '4566206088344615922'])`

should return
```
{ 'foo' : '4566206088344615922' }
```

### Actual Behaviour

It returns

```
{ 'foo' : 4566206088344616000 }
```

So there's two problems -- a generic problem where numeric values are returned as numbers, not strings and a specific "large number" problem where some large numbers result in a different problem.

I did a hacky fix to unblock someone in `aio-cli-plugin-cloudmanager` https://github.com/adobe/aio-cli-plugin-cloudmanager/pull/254/files#diff-eb63176ac949781c5f148f8fa793376af1d1984151f56bd84631f9e8320f29b7R77

Will think some more about a better solution. But I also wanted to create this issue because, AFAICT, `aio-lib-runtime` has the same problem.

**Comment by purplecabbage** [comment]
Verified:
  ● createKeyValueObjectFromFlag › return expected large number

    expect(received).toMatchObject(expected)

    - Expected
    + Received

      Object {
    -   "foo": "4566206088344615922",
    +   "foo": 4566206088344616000,
      }

**Comment by purplecabbage** [comment]
Cannot really fix the bigger than integer issue ...
```node
> console.log('number = ', 4566206088344615922)
number =  4566206088344616000
```
